GET http://localhost:8001/getarticle?title=service
# Content-Type: application/json

# {
# "author": "Steve hello Gelsi",
# "title": "Tesla hello reaches milestone on autopilot efforts",
# "description": "Tesla Inc. founder Elon Musk on Thursday said the company's full self-driving beta is now available to any Tesla owner in North America who requests it on their car screen, if they have bought the option. In a Tweet, Musk congratulated the Tesla autopilot and…",
# "url": "https://www.marketwatch.com/story/tesla-reaches-milestone-on-autopilot-efforts-2022-11-25",
# "urlToImage": "https://s.wsj.net/public/resources/MWimages/MW-GP644_MicroS_ZG_20180906154215.jpg",
# "publishedAt": "2022-11-25T14:41:42Z",
# "content": "Tesla Inc. \r\n TSLA,\r\n -1.15%\r\nfounder Elon Musk on Thursday said the company's full self-driving beta is now available to any Tesla owner in North America who requests it on their car screen, if they… [+281 chars]"
# }